'use strict';

module.exports = {
    lk_aichach_friedberg: {
        title: 'LK Aichach Friedberg',
        url: 'https://lra-aic-fdb.de/',
        customer: 'aic-fdb',
        requestedWith: 'com.webapp.aic-fdb',
    },
    lk_altenkirchen: {
        title: 'LK Altenkirchen',
        url: 'https://www.awb-ak.de/',
        customer: 'awb-ak',
        requestedWith: 'com.webapp.awb-ak',
    },
    lk_ansbach: {
        title: 'LK Ansbach',
        url: 'https://www.landkreis-ansbach.de/',
        customer: 'ansbach',
        requestedWith: 'com.webapp.ansbach',
    },
    lk_aschaffenburg: {
        title: 'LK Aschaffenburg',
        url: 'https://www.landkreis-aschaffenburg.de/',
        customer: 'lra-ab',
        requestedWith: 'com.webapp.lra-ab',
    },
    lk_bad_duerkheim: {
        title: 'LK Bad Dürkheim',
        url: 'http://awb.kreis-bad-duerkheim.de/',
        customer: 'awb-duerkheim',
        requestedWith: 'com.webapp.awb-duerkheim',
    },
    lk_bad_toelz: {
        title: 'LK Bad Tölz - Wolfratshausen',
        url: 'https://wgv-quarzbichl.de/',
        customer: 'wgv',
        requestedWith: 'com.webapp.wgv',
    },
    lk_bgl: {
        title: 'LK Berchtesgadener Land',
        url: 'https://www.lra-bgl.de/',
        customer: 'bgl',
        requestedWith: 'com.webapp.bgl',
    },
    burbach: {
        title: 'Burbach',
        url: 'https://www.burbach-siegerland.de/',
        customer: 'burbach',
        requestedWith: 'com.webapp.burbach',
    },
    lk_coburg: {
        title: 'LK Coburg',
        url: 'https://www.landkreis-coburg.de/',
        customer: 'coburg',
        requestedWith: 'com.webapp.coburg',
    },
    lk_dachau: {
        title: 'LK Dachau',
        url: 'https://www.landratsamt-dachau.de/',
        customer: 'lra-dah',
        requestedWith: 'com.webapp.lra-dah',
    },
    lk_erding: {
        title: 'LK Erding',
        url: 'https://www.landkreis-erding.de/',
        customer: 'erding',
        requestedWith: 'com.webapp.erding',
    },
    fulda: {
        title: 'Fulda',
        url: 'https://www.fulda.de/',
        customer: 'fulda-stadt',
        requestedWith: 'com.webapp.fulda-stadt',
    },
    lk_fulda: {
        title: 'LK Fulda',
        url: 'https://www.landkreis-fulda.de/',
        customer: 'fulda',
        requestedWith: 'com.webapp.fulda',
    },
    lk_ffb: {
        title: 'LK Fürstenfeldbruck',
        url: 'https://www.awb-ffb.de/',
        customer: 'ffb',
        requestedWith: 'com.webapp.ffb',
    },
    lk_giessen: {
        title: 'LK Gießen',
        url: 'https://www.giessen.de/',
        customer: 'lkgi',
        requestedWith: 'com.webapp.lkgi',
    },
    lk_gotha: {
        title: 'LK Gotha',
        url: 'https://www.landkreis-gotha.de/',
        customer: 'gotha',
        requestedWith: 'com.webapp.gotha',
    },
    lk_guenzburg: {
        title: 'LK Günzburg',
        url: 'https://kaw.landkreis-guenzburg.de/',
        customer: 'kaw-guenzburg',
        requestedWith: 'com.webapp.kaw-guenzburg',
    },
    lk_hassberge: {
        title: 'LK Haßberge',
        url: 'https://awhas.de/',
        customer: 'awhas',
        requestedWith: 'com.webapp.awhas',
    },
    lk_hersfeld_rotenburg: {
        title: 'LK Hersfeld Rotenburg',
        url: 'https://www.azv-hef-rof.de/',
        customer: 'azv-hef-rof',
        requestedWith: 'com.webapp.azv-hef-rof',
    },
    kaufbeuren: {
        title: 'Kaufbeuren',
        url: 'https://www.kaufbeuren.de/',
        customer: 'kaufbeuren',
        requestedWith: 'com.webapp.kaufbeuren',
    },
    lk_kelheim: {
        title: 'LK Kelheim',
        url: 'https://www.landkreis-kelheim.de/',
        customer: 'kelheim',
        requestedWith: 'com.webapp.kelheim',
    },
    lk_kulmbach: {
        title: 'LK Kulmbach',
        url: 'https://www.landkreis-kulmbach.de/',
        customer: 'kulmbach',
        requestedWith: 'com.webapp.kulmbach',
    },
    lk_kronach: {
        title: 'LK Kronach',
        url: 'https://www.landkreis-kronach.de',
        customer: 'kronach',
        requestedWith: 'com.webapp.kronach',
    },
    lk_lahn_dill: {
        title: 'LK Lahn Dill',
        url: 'https://www.awld.de/',
        customer: 'awld',
        requestedWith: 'com.webapp.awld',
    },
    memmingen: {
        title: 'Memmingen',
        url: 'https://umwelt.memmingen.de/',
        customer: 'memmingen',
        requestedWith: 'com.webapp.memmingen',
    },
    lk_muehldorf: {
        title: 'LK Mühldorf am Inn',
        url: 'https://www.lra-mue.de/',
        customer: 'lra-mue',
        requestedWith: 'com.webapp.lra-mue',
    },
    muenchen_suedost: {
        title: 'München Südost',
        url: 'https://www.zvmso.de/',
        customer: 'zv-muc-so',
        requestedWith: 'com.webapp.zv-muc-so',
    },
    lk_neuburg_schrobenhausen: {
        title: 'LK Neuburg Schrobenhausen',
        url: 'https://www.landkreisbetriebe.de/',
        customer: 'landkreisbetriebe',
        requestedWith: 'com.webapp.landkreisbetriebe',
    },
    lk_neustadt_waldnaab: {
        title: 'LK Neustadt a.d. Waldnaab',
        url: 'https://www.neustadt.de/',
        customer: 'neustadt',
        requestedWith: 'com.webapp.neustadt',
    },
    nordschwaben: {
        title: 'Nordschwaben',
        url: 'https://www.awv-nordschwaben.de/',
        customer: 'awv-nordschwaben',
        requestedWith: 'com.webapp.awv-nordschwaben',
    },
    pullach: {
        title: 'Pullach',
        url: 'https://www.pullach.de/',
        customer: 'pullach',
        requestedWith: 'com.webapp.pullach',
    },
    regensburg: {
        title: 'Regensburg',
        url: 'https://www.regensburg.de/',
        customer: 'regensburg',
        requestedWith: 'com.webapp.regensburg',
    },
    lk_regensburg: {
        title: 'LK Regensburg',
        url: 'https://www.landkreis-regensburg.de/',
        customer: 'lra-regensburg',
        requestedWith: 'com.webapp.lra-regensburg',
    },
    lk_rems_murr: {
        title: 'LK Rems-Murr AöR',
        url: 'https://www.abfallwirtschaft-rems-murr.de/',
        customer: 'rmk',
        requestedWith: 'com.webapp.rmk',
    },
    lk_rosenheim: {
        title: 'LK Rosenheim',
        url: 'https://www.abfall.landkreis-rosenheim.de/',
        customer: 'rosenheim',
        requestedWith: 'com.webapp.rosenheim',
    },
    lk_roth: {
        title: 'LK Roth',
        url: 'https://www.landratsamt-roth.de/',
        customer: 'roth',
        requestedWith: 'com.webapp.roth',
    },
    lk_rottal_dingolfing: {
        title: 'LK Rottal-Inn und Dingolfing-Landau',
        url: 'https://www.awv-isar-inn.de/',
        customer: 'awv-isar-inn',
        requestedWith: 'com.webapp.awv-isar-inn',
    },
    lk_zaso: {
        title: 'LK Saale-Orla und Saalfeld-Rudolstadt',
        url: 'https://www.zaso-online.de/',
        customer: 'zaso',
        requestedWith: 'com.webapp.zaso',
    },
    lk_schweinfurt: {
        title: 'LK Schweinfurt',
        url: 'https://www.landkreis-schweinfurt.de/',
        customer: 'lra-schweinfurt',
        requestedWith: 'com.webapp.lra-schweinfurt',
    },
    lk_suedliche_weinstrasse: {
        title: 'LK Südliche Weinstrasse',
        url: 'https://www.suedliche-weinstrasse.de/',
        customer: 'eww-suew',
        requestedWith: 'com.webapp.eww-suew',
    },
    lk_tirschenreuth: {
        title: 'LK Tirschenreuth',
        url: 'https://www.awz-tir.de/',
        customer: 'kreis-tir',
        requestedWith: 'com.webapp.kreis-tir',
    },
    lk_tuebingen: {
        title: 'LK Tübingen',
        url: 'https://www.abfall-kreis-tuebingen.de/',
        customer: 'tuebingen',
        requestedWith: 'com.webapp.tuebingen',
    },
    unterhaching: {
        title: 'Unterhaching',
        url: 'https://www.unterhaching.de/',
        customer: 'unterhaching',
        requestedWith: 'com.webapp.unterhaching',
    },
    unterschleissheim: {
        title: 'Unterschleißheim',
        url: 'https://www.unterschleissheim.de/',
        customer: 'unterschleissheim',
        requestedWith: 'com.webapp.unterschleissheim',
    },
    allmannshofen: {
        title: 'Allmannshofen [Kein Müll]',
        url: 'https://www.allmannshofen.de/',
        customer: 'allmannshofen',
        requestedWith: 'com.webapp.allmannshofen',
    },
    heretsried: {
        title: 'Heretsried [Kein Müll]',
        url: 'https://heretsried.de/',
        customer: 'heretsried',
        requestedWith: 'com.webapp.heretsried',
    },
    hyeonsil: {
        title: 'Tae Kwon Do Bruderschule Hyeonsil [Kein Müll]',
        url: 'https://hyeonsil.de/',
        customer: 'hyeonsil',
        requestedWith: 'com.webapp.hyeonsil',
    },
    vdi_koblenz: {
        title: 'VDI Mittelrheinischer Bezirksverein [Kein Müll]',
        url: 'https://www.vdi.de/',
        customer: 'vdi-koblenz',
        requestedWith: 'com.webapp.vdi-koblenz',
    },
};
